### ISSUE TITLE
[FEATURE] Add integration tests to `Redis`

### ISSUE THREAD

**Issue by guibranco** [guibranco/CrispyWaffle#543]
### Description

Add integration tests project using a real `Redis` instance in `AppVeyor` and a `docker-compose.yml` to spin up Redis.

### Tech notes

Add a `Redis` instance to the build pipeline (`appveyor.yml`):

Redis 3.0.1 **(deprecated)**
```yml
before_build:
- choco install redis-64
- redis-server --service-install
```

Redis 5.0.14 **(port)**
```yml
install:
  - ps: (new-object net.webclient).DownloadFile('https://github.com/tporadowski/redis/releases/download/v5.0.14.1/Redis-x64-5.0.14.1.msi', 'Redis-x64-5.0.14.1.msi')
  - ps: msiexec /i Redis-x64-5.0.14.1.msi /quiet /norestart
```

Create the `CripsyWaflle.IntegrationTests` and add the Redis directory with the `RedisCacheRepositoryTests`.
