### ISSUE TITLE
[FEATURE] Add InferSharp workflow

### ISSUE THREAD

**Issue by guibranco** [guibranco/CrispyWaffle#617]
Implement a new GitHub Actions workflow to integrate [InferSharp](https://github.com/microsoft/infersharp) into this repository. This will enable static analysis to detect null dereference issues and improve code quality.

#### Workflow Details
The workflow should:
- Trigger on pushes and pull requests to the `main` branch.
- Run InferSharp analysis.
- Upload the SARIF output to the GitHub Security Center.

#### Reference
Use the following workflow implementation as a reference:  [InferSharp Workflow](https://github.com/guibranco/dotnet-aicommitmessage/blob/main/.github/workflows/infersharp.yml)

#### Workflow Code
Add the following YAML configuration as `.github/workflows/infersharp.yml` in the repository:

```yml
name: InferSharp
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  infer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Infer#
        uses: microsoft/infersharpaction@v1.5
        id: runinfersharp

      - name: Upload SARIF output to GitHub Security Center
        uses: github/codeql-action/upload-sarif@v2
        if: success() && hashFiles('infer-out/report.sarif') != ''
        with:
          sarif_file: infer-out/report.sarif
        continue-on-error: true
```

#### Acceptance Criteria
1. The `.github/workflows/infersharp.yml` file is added to each C# repository.
2. The workflow triggers correctly on `push` and `pull_request` events to the `main` branch.
3. InferSharp successfully analyzes the code and generates a SARIF report.
4. SARIF output is uploaded to the GitHub Security Center.
