### ISSUE TITLE
[FEATURE] Add CodeQL workflow to repository

### ISSUE THREAD

**Issue by guibranco** [guibranco/CrispyWaffle#618]
Implement a new GitHub Actions workflow to integrate [CodeQL](https://github.com/github/codeql-action) analysis into the repository. This will provide automated code scanning to detect vulnerabilities and improve code quality.

#### Workflow Details
The workflow should:
- Trigger on pushes and pull requests to the `main` branch.
- Automatically schedule weekly scans every Tuesday at 2:36 AM (UTC).
- Analyze C# code in the repository.

#### Reference
Use the following workflow implementation as a reference:  [CodeQL Workflow](https://github.com/guibranco/dotnet-aicommitmessage/blob/main/.github/workflows/codeql.yml)

#### Workflow Code
Add the following YAML configuration as `.github/workflows/codeql.yml` in the repository:

```yml
# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: "CodeQL"

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '36 2 * * 2'

jobs:
  analyze:
    name: Analyze
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
```

#### Acceptance Criteria
1. The `.github/workflows/codeql.yml` file is added to the repository.
2. The workflow triggers correctly on `push` and `pull_request` events to the `main` branch.
3. A scheduled scan runs weekly every Tuesday at 2:36 AM (UTC).
4. CodeQL successfully analyzes the C# code and provides a detailed security report.
